import User from '@/screens/User/User'
import { GetServerSidePropsContext } from 'next'
import Head from 'next/head'

export default function UserPage({ demoUrl }: any) {
  return (
    <>
      <Head>
        <title>chatif.ai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <User demoUrl={demoUrl} />
    </>
  )
}

export async function getServerSideProps(context: any) {
  const { url } = context.params
  return {
    props: {
      demoUrl: url
    }, 
  }
}