import User from '@/screens/User/User'
import Head from 'next/head'

export default function UserPage() {
  return (
    <>
      <Head>
        <title>chatif.ai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <User />
    </>
  )
}
